### DISCUSSION TITLE
Uplift release includes changelog creation by default. New flags for skipping

### DISCUSSION THREAD

**Discussion by ga-paul-t** [gembaadvantage/uplift#112] [Announcements]
The `uplift release` command has recently had some additional flags introduced to optionally skip parts of the workflow:

- `--skip-changelog`: skip the creation of amendment of a CHANGELOG.md
- `--skip-bumps`: skip the bumping of files

Your existing GitHub workflows may need to be updated to include one of these flags to maintain previous behaviour. For example the GitHub Action may now need to be updated to look like the following:

```yaml
- name: Release
  if: github.ref == 'refs/heads/main'
  uses: gembaadvantage/uplift-action@v2.0.1
  with:
    args: release --skip-changelog
  env:
    GITHUB_TOKEN: ${{ secrets.GH_UPLIFT }}
```
