### DISCUSSION TITLE
JSON, TOML & YAML support

### DISCUSSION THREAD

**Discussion by PurpleBooth** [gembaadvantage/uplift#86] [Ideas]
Along side regex it would be really powerful to be able to specify a path to update in JSON or TOML or YAML

```yaml
  - 
    file: ./package.json
    json: 'version'
  - 
    file: ./package.json
    json: 'some-key.something.version'
```

It sort of sucked writing a regex to update my package JSON (not un-doable, just a bit of a faff). Most languages use one of those 3 file formats for their package details file, so it might be worth making it easier to bump with that.
