### ISSUE TITLE
[Feature]: enhance bumping of files by supporting multiple regex expressions

### ISSUE THREAD

**Issue by ga-paul-t** [gembaadvantage/uplift#102]
### Describe your feature

`uplift` supports the bumping of files by using regex pattern matching. However, the config is designed to only match the version in a single place, which may not always be true with all file types. The current solution would require multiple definitions for the same file, which is not that practical.

### Your potential solution

Extend the config to support multiple regex definitions for a single file:

```yaml
bumps:
  - file: ./Chart.yaml
    regex:
      - pattern: "version: $VERSION"
        count: 1
        semver: true
      - pattern: "appVersion: $VERSION"
        count: 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
