### ISSUE TITLE
[Feature]: enhance bumping of YAML files using YAML paths

### ISSUE THREAD

**Issue by ga-paul-t** [gembaadvantage/uplift#104]
### Describe your feature

File bumping only supports version detection through regular expressions at present. This works as a nice catch-all mechanism for custom file types within a repository. However, when dealing with YAML files, it would be much simpler (and provide a better developer experience) to support the use of YAML paths to locate and replace a version.

### Your potential solution

Expand the existing config to support the inclusion of a YAML path(s) when defining a bump.

```yaml
bumps:
  - 
    file: ./Chart.yaml
    json: 
       - path: 'version'
         semver: true
       - path: 'appVersion'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
