### ISSUE TITLE
[Bug]: uplift binary should be installed under a common path rather than at custom location

### ISSUE THREAD

**Issue by ga-paul-t** [gembaadvantage/uplift#154]
### What happened?

When using Cirrus CI. The uplift binary isn't found unless a custom path is provided. This makes integration with other potential CI providers cumbersome.

### Steps to reproduce it

1. Create a cirrus ci YAML file:
```yaml
# .cirrus.yml
task:
  name: Release
  only_if: $BRANCH == "main"
  container:
    image: gembaadvantage/uplift:latest
  script: uplift release
```
2. Push a change to a repository to trigger a build within cirrus ci. The following build output is expected:
```sh
uplift release
/tmp/scripts52fdfc072182654f163f5f0f9a621d72.sh: line 4: uplift: not found
Exit status: 127
```

### Which version?

v2.6.0

### Which operating system(s) are you using?

All

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
