### ISSUE TITLE
[Bug]: fetch tags option is ignored during release

### ISSUE THREAD

**Issue by ga-paul-t** [gembaadvantage/uplift#156]
### What happened?

When testing uplift on Cirrus CI, it does not retrieve all of the tags by default. Uplift has the option to fetch all tags during a release, but this is sadly ignored.

### Steps to reproduce it

1. Write a cirrus YAML file:
```yaml
# .cirrus.yml

task:
  name: Release
  only_if: $BRANCH == "main" && $CIRRUS_TAG == ""
  # depends_on:
  container:
    image: gembaadvantage/uplift:latest
  before_script:
    - CLONE_URL=${CIRRUS_REPO_CLONE_URL#"https://"}
    - git remote set-url origin "https://${GITHUB_TOKEN}@${CLONE_URL}"
  release_script:
    - uplift release --fetch-all
  environment:
    GITHUB_TOKEN: ENCRYPTED[!1497b201beb7fb1075827a5e47896cd2d82076bdba50a003b06be04333d9b17fb80475fccb8d7744dad71a55a4e2c293!]
```
2. View the failure in the build:
```sh
uplift release --fetch-all
   • latest commit            
      • retrieved latest commit   author=********** email=*********** message=feat: this is a new feature
   • current version          
      • repository not tagged with version
   • next version             
      • identified first version  commit=feat: this is a new feature current= next=0.1.0
   • next commit              
      • changes will be committed with email=*********** message=ci(uplift): uplifted for version 0.1.0 name=************
   • detect scm               
      • no recognised scm provider detected
   • bump                     
      • no files to bump         
   • changelog                
      • pre-tagging latest commit for changelog creation tag=0.1.0
      • determine changes for release tag=0.1.0
      • changeset identified      commits=56 date=2022-04-18 tag=0.1.0
   • git commit               
      • commit outstanding changes
      • pushing commit to remote 
   • git tag                  
      • identified next tag       tag=0.1.0
      • tagged repository with standard tag
      • pushing tag to remote    
Error: To https://github.com/ga-paul-t/test-uplift.git
 ! [rejected]        0.1.0 -> 0.1.0 (already exists)
error: failed to push some refs to 'https://github.com/ga-paul-t/test-uplift.git'
hint: Updates were rejected because the tag already exists in the remote.
```

### Which version?

v2.6.1

### Which operating system(s) are you using?

All

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
