### ISSUE TITLE
[Feature]: Customisable commit details associated with release

### ISSUE THREAD

**Issue by ga-paul-t** [gembaadvantage/uplift#16]
### Describe your feature

Allow the commit used by uplift during a release to be customisable. This offers greater flexibility to users when integrating uplift into their CI process.

### Your potential solution

Support additional configuration options within the `.uplift.yml` file:

```yaml
commit:
  message: an optional customisable message can be provided here
  author: joe.bloggs
  email: joe.bloggs@gmail.com
```
Only basic validation is required and uplift should fall back to the default commit message if needed. An author and email must be provided together for uplift to not impersonate the user who initiated the bump
