### ISSUE TITLE
[Feature]: Enhance bumping of TOML files

### ISSUE THREAD

**Issue by ga-paul-t** [gembaadvantage/uplift#204]
### Describe your feature

Expand the existing file bumping support to include TOML files.

### Your potential solution

Expand the existing config to support the inclusion of a TOML path(s) when defining a bump.

```yaml
bumps:
  - 
    file: ./config.toml
    toml: 
       - path: 'version'
         semver: true
```

Libraries exist to convert TOML into JSON and back.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ga-paul-t** [comment]
https://github.com/TomWright/dasel

Has the ability to modify any values within YAML, TOML, JSON, XML and CSV files

**Comment by ga-paul-t** [comment]
Proposing a new simplified strategy for bumping files:

```yaml
bumps:
  - file: Chart.yaml
    regex:
    json: #deprecated
    selectors:
      # Raw string
      - ".path.path.path"
      
      # Complex type
      - path: ".path.path.path"
        value: # support templated values {{.Tag}} {{.SemverTag}} defaults to {{.Tag}}
```
