### ISSUE TITLE
[Feature]: hooks can define timeouts to prevent uplift from hanging for long periods of time

### ISSUE THREAD

**Issue by ga-paul-t** [gembaadvantage/uplift#206]
### Describe your feature

Expand the hook functionality to include an optional timeout. This is to prevent any scripts or shell commands from running for an unexpected period of time, causing uplift to hang.

### Your potential solution

Update the hooks config to support a simple and complex hook syntax:

```yaml
hooks:
  timeout: 2s
  before:
    - cmd: ./script.sh
      timeout: 5s
    - ./different-script.sh
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
