### ISSUE TITLE
[Bug]: Patch not bumped

### ISSUE THREAD

**Issue by tony-engineering** [gembaadvantage/uplift#267]
### What happened?

Hello,
I enjoy Uplift because it is simple to configure, but I have a problem. Something is not working as expected. Uplift can only successfully create Minor versions (when I have a "feat:" commit for example). But for the case of Patch, it doesn't work, see logs below:
```
$ uplift --debug --no-push bump --prerelease beta.1
   • checking git             
      • checking if git is installed
      • checking for git repo     cwd=/builds/domain.net/mint
      • checking if repository is dirty
      • checking for detached head
      • checking if shallow clone used
   • next semantic version    
      • largest increment detected from commits increment=Patch
      • appending prerelease version metadata= prerelease=beta.1
      • identified next semantic version version=1.21.0-beta.1
   • building next commit     
      • overwriting commit author name from uplift config
      • overwriting commit author email from uplift config
      • overwriting commit message from uplift config
      • changes will be committed with email=tech.team@domain.net message=ci: bumped version [skip ci] name=Tech Team
   • bumping files            
      • attempting file bump      count=0 file=./README.md regex=$VERSION semver=true
      • skipping bump             current=1.21.0-beta.1 file=./README.md next=1.21.0-beta.1
      • attempting file bump      count=0 file=./current-version.txt regex=$VERSION semver=true
      • skipping bump             current=1.21.0-beta.1 file=./current-version.txt next=1.21.0-beta.1
      • attempting file bump      file=./package.json path=version semver=true
      • file bumped               current=1.21.0-beta.1 file=./package.json next=1.21.0-beta.1
      • successfully staged file  file=./package.json
      • attempting file bump      count=0 file=./k8s-manifests/api-pod.yaml regex=api:$VERSION semver=true
      • skipping bump             current=1.21.0-beta.1 file=./k8s-manifests/api-pod.yaml next=1.21.0-beta.1
      • attempting file bump      count=0 file=./k8s-manifests/db-migrator-pod.yaml regex=db-migrator:$VERSION semver=true
      • skipping bump             current=1.21.0-beta.1 file=./k8s-manifests/db-migrator-pod.yaml next=1.21.0-beta.1
      • attempting file bump      count=0 file=./k8s-manifests/web-pod.yaml regex=web:$VERSION semver=true
      • skipping bump             current=1.21.0-beta.1 file=./k8s-manifests/web-pod.yaml next=1.21.0-beta.1
      • bumped files staged       count=1
   • committing changes       
      • no files staged skipping push
```
It says `identified next semantic version version=1.21.0-beta.1`, but it actually should be `version=1.21.1-beta.1`.
Anyone has a clue here ? thanks

### Steps to reproduce it

Use a config similar to the one I provided, create a "fix" (edited) commit, then try to apply the `uplift --debug --no-push bump --prerelease beta.1` command.

### Your uplift configuration

```YAML
bumps:
  - file: ./README.md
    regex:
      - pattern: "$VERSION"
        semver: true
        count: 0
  - file: ./current-version.txt
    regex:
      - pattern: "$VERSION"
        semver: true
        count: 0
  - file: ./package.json
    json:
      - path: "version"
        semver: true
  - file: ./k8s-manifests/api-pod.yaml
    regex:
      - pattern: "api:$VERSION"
        semver: true
        count: 0
  - file: ./k8s-manifests/db-migrator-pod.yaml
    regex:
      - pattern: "db-migrator:$VERSION"
        semver: true
        count: 0
  - file: ./k8s-manifests/web-pod.yaml
    regex:
      - pattern: "web:$VERSION"
        semver: true
        count: 0
commitMessage: "ci: bumped version [skip ci]"
commitAuthor:
  name: "Tech Team"
  email: "tech.team@domain.net"
```
```


### Which version?

The one used by gembaadvantage/uplift Docker image.

### Which operating system(s) are you using?

Linux

### Optional debug output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ga-paul-t** [comment]
Hi @tony-engineering. Thanks for raising this issue. I'll take a look

**Comment by ga-paul-t** [comment]
Would you be able to provide me with a snapshot of your git log? I have just tried the following, and it worked as expected. I am curious as I can see that it has detected a patch but calculated the next version as a minor.

```sh
commit 6f9a84d9d1ff9e29fd113874a8b03480edafc836
Author: paul.t <paul.t@gembaadvantage.com>
Date:   Wed Oct 5 10:46:12 2022 +0100

    docs: this is just some docs

commit d1b9027297819031d9f8c664070758e574993021
Author: paul.t <paul.t@gembaadvantage.com>
Date:   Wed Oct 5 10:46:09 2022 +0100

    fix: a bug fix

commit ffc4c481751143efd06b8e1129e767a46312590d
Author: paul.t <paul.t@gembaadvantage.com>
Date:   Wed Oct 5 10:46:04 2022 +0100

    ci: this is just a ci change

commit aff795b767716620582d23db3f501247d3b3e6ad (tag: v0.1.0)
Author: paul.t <paul.t@gembaadvantage.com>
Date:   Wed Oct 5 10:43:52 2022 +0100

    feat: a new feature
```

Then I run `uplift --debug --no-push bump --prerelease beta.1`, I get the following output:

```sh
uplift --debug --no-push bump --prerelease beta.1
   • checking git
      • checking if git is installed
      • checking for git repo     cwd=/dev/github.com/gembaadvantage/uplift-bug
      • checking if repository is dirty
      • checking for detached head
      • checking if shallow clone used
   • next semantic version
      • largest increment detected from commits increment=Patch
      • appending prerelease version metadata= prerelease=beta.1
      • identified next semantic version version=v0.1.1-beta.1
   • building next commit
      • overwriting commit author name from uplift config
      • overwriting commit author email from uplift config
      • overwriting commit message from uplift config
      • overwriting commit author from git config
      • changes will be committed with email=paul.t@gembaadvantage.com message=ci: bumped version [skip ci] name=paul.t
   • bumping files
      • attempting file bump      count=0 file=README.md regex=$VERSION semver=true
      • trimming 'v' prefix from version
      • file bumped               current=v0.1.0 file=README.md next=v0.1.1-beta.1
      • successfully staged file  file=README.md
      • bumped files staged       count=1
   • committing changes
      • attempting to commit changes
      • staged changes committed
      • skipping push of commit to remote
```

**Comment by tony-engineering** [comment]
Thanks for the quick reply. Our history looks like this (I checked out the commit that triggered the bump job mentioned above):
```
commit caa979ac7c8a8e57fb58dac82a55af64ce5b1931 (HEAD)
Merge: 37dd7ca1 1546b31b
Author: S A <>
Date:   Tue Oct 4 09:23:11 2022 +0000

    fix(web): removes SMTH from tab name
    
    Closes MINT-327.
    
    Commits:
    * removes SMTH from tab name

commit 37dd7ca15f529378f63af62b7955c16b7ca5ac64
Merge: 7f366788 90336d03
Author: S A <>
Date:   Tue Oct 4 07:32:26 2022 +0000

    docs: update the readme file with the command to reset the database migration
    
    .
    
    Commits:
    * update the readme file with the command to reset the database migration

commit 7f36678858e1c72667fa597ebe71b976c542f5ea
Merge: 5304bf66 3f39bef0
Author: C S <>
Date:   Mon Oct 3 16:53:36 2022 +0000

    fix: I made the following fields are mandatory:
    status,country,action,turbine_id
    
    Closes MINT-312
    
    Closes MINT-312.
    
    Commits:
    * make variableId from maintenace table optionally
    
    * make variableId from maintenace table optionally
```

Our workflow is the following (we use Gitlab):

1.     Developer creates a branch + MR
2.     Developer writes a meaningful description for the MR.
3.     Developer creates and pushed commits
4.     Developer marks the MR as “Ready”
5.     Reviewers check and approve MR
6.     Developer goes to MR and clicks “Edit commit message”
7.     Developers adjusts the “Merge commit message” following the convention. 

In the UI, when we display a commit from master (when the bump happens), it looks like this:
![image](https://user-images.githubusercontent.com/9582205/194042648-cd04c61d-63bf-479a-8332-990a71badee3.png)

**Comment by ga-paul-t** [comment]
Awesome. Thanks for all the information. I have access to a GitLab instance, so I can try it out there.

So before that job was run, what was the current tag in the repository? Can I ask what merging strategy you use? And are you running Uplift in the same way as defined in the document: https://upliftci.dev/ci/gitlab/ ?

**Comment by tony-engineering** [comment]
Here is the log output from the `release` job that is run at the end of the pipeline.
```
$ uplift --debug release --prerelease beta.1
   • checking git             
      • checking if git is installed
      • checking for git repo     cwd=/builds/domain.net/mint
      • checking if repository is dirty
      • checking for detached head
      • checking if shallow clone used
   • detecting scm provider   
      • parsing repository remote
      • scm provider identified   scm=GitLab
   • next semantic version    
      • largest increment detected from commits increment=Patch
      • appending prerelease version metadata= prerelease=beta.1
      • identified next semantic version version=1.21.0-beta.1
   • building next commit     
      • overwriting commit author name from uplift config
      • overwriting commit author email from uplift config
      • overwriting commit message from uplift config
      • changes will be committed with email=tech.team@domain.net message=ci: bumped version [skip ci] name=Tech Team
   • bumping files            
      • attempting file bump      count=0 file=./README.md regex=$VERSION semver=true
      • skipping bump             current=1.21.0-beta.1 file=./README.md next=1.21.0-beta.1
      • attempting file bump      count=0 file=./current-version.txt regex=$VERSION semver=true
      • skipping bump             current=1.21.0-beta.1 file=./current-version.txt next=1.21.0-beta.1
      • attempting file bump      file=./package.json path=version semver=true
      • file bumped               current=1.21.0-beta.1 file=./package.json next=1.21.0-beta.1
      • successfully staged file  file=./package.json
      • attempting file bump      count=0 file=./k8s-manifests/api-pod.yaml regex=api:$VERSION semver=true
      • skipping bump             current=1.21.0-beta.1 file=./k8s-manifests/api-pod.yaml next=1.21.0-beta.1
      • attempting file bump      count=0 file=./k8s-manifests/db-migrator-pod.yaml regex=db-migrator:$VERSION semver=true
      • skipping bump             current=1.21.0-beta.1 file=./k8s-manifests/db-migrator-pod.yaml next=1.21.0-beta.1
      • attempting file bump      count=0 file=./k8s-manifests/web-pod.yaml regex=web:$VERSION semver=true
      • skipping bump             current=1.21.0-beta.1 file=./k8s-manifests/web-pod.yaml next=1.21.0-beta.1
      • bumped files staged       count=1
   • generating changelog     
      • pre-tagging latest commit for changelog creation tag=1.21.0-beta.1
      • determine changes for release tag=1.21.0-beta.1
      • no log entries between tags prev=1.21.0-beta.1 tag=1.21.0-beta.1
   • committing changes       
      • no files staged skipping push
   • tagging repository       
      • no version change detected current=1.21.0-beta.1 next=1.21.0-beta.1
```

before that job was run, the current tag in the repository was: `1.21.0-beta.1`
merge strategy is this one
![image](https://user-images.githubusercontent.com/9582205/194105318-4f52d135-dcee-4168-b66c-309cb1b532e8.png)
Commits squash is enforced.

Here is the config of the release job:
```
release:
  stage: release
  rules: !reference [.conditions, on_success_on_master]
  image:
    name: gembaadvantage/uplift
    entrypoint: [""]
  variables:
    GIT_DEPTH: 0
  before_script:
    - PROJECT_URL=${CI_PROJECT_URL#"https://"}
    - git remote set-url origin "https://oauth2:${GITLAB_TOKEN}@${PROJECT_URL}.git"
  script:
    # GitLab by default checks out a detached HEAD
    - git checkout $CI_COMMIT_REF_NAME
    # Make a beta release (this time commit new version)
    - uplift --debug release --prerelease beta.1
  dependencies: []
```
I see that we didnt put the rule `'$CI_PIPELINE_SOURCE == "merge_request_event"'`, but we have this for on_success_on_master:
```
.conditions:
  on_success_on_master:
    - if: '$CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH'
      when: never
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      when: on_success
```
