### ISSUE TITLE
[Bug]: Use Env Vars for commit author

### ISSUE THREAD

**Issue by Bastianowicz** [gembaadvantage/uplift#280]
### What happened?

When setting up uplift it would be good to use env vars for commit author configuration as well. Thus one could use GITLAB_USER_NAME and GITLAB_USER_EMAIL as the commit author.

### Steps to reproduce it

1. Configure uplift to use commitauthor with env vars (see config below)
2. Run uplift release, passing the vars in `docker run --rm -v $PWD:/tmp -e GITLAB_USER_NAME=bastianowicz -e GITLAB_USER_EMAIL=bastiano@example.com -w /tmp gembaadvantage/uplift release --no-push --debug`

## Expected
* Commit Message to be authored by "bastianowicz <bastiano@example.com>"

## Received
* Commit Message to be authored by "$GITLAB_USER_NAME <$GITLAB_USER_EMAIL>"

### Your uplift configuration

```YAML
bumps:
  - file: composer.json
    json:
      - path: "version"
        semver: true
  - file: package.json
    json:
      - path: "version"
        semver: true
commitAuthor:
  name: $GITLAB_USER_NAME
  email: $GITLAB_USER_EMAIL
changelog:
  exclude:
    - '^chore\(deps\)'
    - ^docs
    - ^ci
```

### Which version?

v2.18.1

### Which operating system(s) are you using?

Mac

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bastianowicz** [comment]
I found a workaround using hooks

```yaml
hooks:
  before:
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
```
