### ISSUE TITLE
[Feature]: Bump version in files matching glob

### ISSUE THREAD

**Issue by Alxandr** [gembaadvantage/uplift#285]
### Describe your feature

I have multiple package.json files I would like to bump. Currently I have to list them all out (which is easy to forget if I add a new one). It would be great if I could do this:

```yml
bumps:
  - file: '**/package.json'
    json:
      - path: 'version'
        semver: true
```

### Your potential solution

Allow `bumps[].file` to be a glob pattern.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
