### ISSUE TITLE
[Feature]: To skip pre-release tags in changelog

### ISSUE THREAD

**Issue by serebro** [gembaadvantage/uplift#318]
### Describe your feature

To have the ability to skip prerelease tags or tags by regexp in changelog generation.

### Your potential solution

Add an option `uplift changelog --skip-tags "\d+.\d+.\d-.*"` to skip some tags by pattern and generate changelog without them.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ga-paul-t** [comment]
👋 @serebro thanks for raising this issue

**Comment by ga-paul-t** [comment]
So I am thinking of introducing an additional changelog config for this issue (with an accompanying flag `--skip-prerelease`):

```yaml
changelog:
  # Any prerelease will be ignored from the changelog generation
  skipPrerelease: true
```

Say, for example, we have a repository with the following tags:

- 0.2.0
- 0.2.0-beta.2
- 0.2.0-beta.1
- 0.1.0

Is the intended behaviour for a changelog entry to be created that includes all commits between 0.2.0 and 0.1.0 ?
