### ISSUE TITLE
[Feature]: Allow configurable strings to trigger PATCH bump

### ISSUE THREAD

**Issue by 4x0v7** [gembaadvantage/uplift#329]
### Describe your feature

Currently, only commits with `fix:` will trigger a PATCH version bump.

Allow users to configure other text that will trigger a PATCH update.

For example, perhaps I want `docs:` or `dev:` to bump the patch version.

Perhaps this doesn't quite conform to Conventional Commits 1.0.0 but it would a useful addition nonetheless.

### Your potential solution

I can image extending the yaml config with something like this:

```yaml
conventionalCommitPatterns:
  major:
    - "feat!:"
  # minor:
  patch:
    - "docs:"
    - "dev:"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
