### ISSUE TITLE
[Bug]: Can't run bump and tag together

### ISSUE THREAD

**Issue by emilrowland** [gembaadvantage/uplift#44]
### What happened?

If I first run the bump script it will create a commit like "ci(bump): bumped version to v1.1.4" and then it will run the tag script but it will responde with "no change in version needed commit=ci(bump): bumped version to v1.1.4" so the commit never gets a tag.

### Steps to reproduce it

```shell
1. run uplift bump
2. run uplift tag
```

### Your uplift configuration

```yaml
firstVersion: v1.0.0
annotatedTags: false

commitAuthor:
  name: "..."
  email: "..."
bumps:
  - # The path of the file relative to where uplift is executed
    file: ./pubspec.yaml
    regex: "version: $VERSION"
    semver: true
```

### Which version?

1.2.0

### Which operating system(s) are you using?

Linux, Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
