### ISSUE TITLE
[Feature]: add option to filter out commits during changelog creation

### ISSUE THREAD

**Issue by ga-paul-t** [gembaadvantage/uplift#62]
### Describe your feature

Uplift is capable of generating a changelog for every tag that is created on a repository. The diff can contain many different conventional commit messages based on the type of work carried out. Some of these commit messages are prefixed with `chore`, `ci` and `docs` etc. and can prove noisy on a changelog. To allow a user to generate a changelog that is focused on features, bug fixes and breaking changes, for example, certain commit messages should be filtered out

### Your potential solution

Add a section to the configuration file that allows a configurable set of filters to control the type of commit messages contained within a changelog diff. The default behaviour should be to include all commit messages.

A possible config could allow the user to configure an `includes` or an `excludes` list of commit messages:

```yaml
changelog:
  includes:
    - feat
    - fix
    - BREAKING CHANGE
    - *!
  excludes:
    - chore(deps)
    - docs
    - ci
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
