### ISSUE TITLE
[Feature]: enhance bumping of JSON files by supporting JSON paths

### ISSUE THREAD

**Issue by ga-paul-t** [gembaadvantage/uplift#89]
### Describe your feature

File bumping only supports version detection through regular expressions at present. This works as a nice catch-all mechanism for custom file types within a repository. However, when dealing with JSON files, it would be much simpler (_and provide a better developer experience_) to support the use of JSON paths to locate and replace a version.

### Your potential solution

Expand the existing config to support the inclusion of a JSON path(s) when defining a `bump`.

```yaml
bumps:
  - 
    file: ./package.json
    json: 
      - path: 'version'
      - path: 'some-key.something.version'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
